### ISSUE TITLE
Fusesoc sporadically fails to compile Verilator simulation 

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1103]
Sporadically we get the following errors from fusesoc when running `fusesoc --verbose --cores-root . run --target=sim --setup --build lowrisc:systems:top_earlgrey_verilator`. 

```
Traceback (most recent call last):
  File "/home/philipp/.local/bin/fusesoc", line 11, in <module>
    load_entry_point('fusesoc', 'console_scripts', 'fusesoc')()
  File "/home/philipp/src/fusesoc/fusesoc/main.py", line 583, in main
    args.func(cm, args)
  File "/home/philipp/src/fusesoc/fusesoc/main.py", line 268, in run
    flags, args.system_name, args.system, args.backendargs, args.build_root)
  File "/home/philipp/src/fusesoc/fusesoc/main.py", line 316, in run_backend
    system_name=system_name)
  File "/home/philipp/src/fusesoc/fusesoc/edalizer.py", line 53, in __init__
    core.export(files_root, _flags)
  File "/home/philipp/src/fusesoc/fusesoc/capi2/core.py", line 183, in export
    os.makedirs(os.path.join(dst_dir, d))
  File "/usr/lib64/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/philipp/src/opentitan/build/lowrisc_systems_top_earlgrey_verilator_0.1/src/lowrisc_systems_top_earlgrey_0.1/../ip/pinmux/rtl'
```

That's due to `top_earlgrey.core` including files in a directory above the current directory. 

https://github.com/lowRISC/opentitan/blob/16aac4a9e3f0c0beadba3f4c045dc845d40c6300/hw/top_earlgrey/top_earlgrey.core#L34-L43

That's unsupported in fusesoc (https://github.com/olofk/fusesoc/issues/264), as discussed in https://github.com/lowRISC/opentitan/issues/715 (which also contains possible solutions).

**Comment by imphil** [comment]
We haven't seen that issue for a long time, should be resolved.
