### ISSUE TITLE
opentitantool panics when bootstrapping cw310: 'attempt to add with overflow'

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#13477]
At commit d8af32ff61026d72a7586c66870feaa162335654, I'm seeing a opentitantool panic with 'attempt to add with overflow' in [sfdp.rs:449](https://cs.opensource.google/opentitan/opentitan/+/d8af32ff61026d72a7586c66870feaa162335654:sw/host/opentitanlib/src/spiflash/sfdp.rs;l=449).

@cfrantz Based on nothing but the stack trace and git blame, could this have something to do with cfc6ac6b090fde10caaac52fae1acdba76abce22 or f5ba7fd0dfe9f0bb25463f8e4d6243912b8fa019? They both touched the impl of [UpdateProtocol::update() for Eeprom](https://cs.opensource.google/opentitan/opentitan/+/d8af32ff61026d72a7586c66870feaa162335654:sw/host/opentitanlib/src/bootstrap/eeprom.rs;l=47-52).

```
$ ./bazelisk.sh test --cache_test_results=no --test_tag_filters=cw310  --test_output=streamed //sw/device/tests:uart_smoketest
[...]
Invoking: sw/host/opentitantool/opentitantool --rcfile= --logging=info --interface=cw310 --conf=sw/host/opentitantool/config/opentitan_cw310.json --exec=load-bitstream --rom-kind=testrom external/bitstreams/cache/dd97ef8a84a055a0f0b4d730cdf61bcb6535020e/lowrisc_systems_chip_earlgrey_cw310_0.1.bit.orig --exec=bootstrap sw/device/tests/uart_smoketest_prog_fpga_cw310.test_key_0.signed.bin console --exit-failure=(FAIL|FAULT).*\n --exit-success=PASS.*\n --timeout=3600s
[2022-06-30T17:29:17Z INFO  opentitantool::command::load_bitstream] Loading bitstream: "external/bitstreams/cache/dd97ef8a84a055a0f0b4d730cdf61bcb6535020e/lowrisc_systems_chip_earlgrey_cw310_0.1.bit.orig"
[2022-06-30T17:29:17Z INFO  opentitanlib::util::rom_detect] Bitstream file USR_ACCESS value: 0xf32cd682
[2022-06-30T17:29:19Z INFO  opentitanlib::util::rom_detect] Did not detect the ROM identification message.
[2022-06-30T17:29:19Z INFO  opentitanlib::transport::cw310] Programming the FPGA bitstream.
[2022-06-30T17:29:35Z INFO  opentitantool] Command result: success.
[2022-06-30T17:29:35Z INFO  opentitanlib::bootstrap] Asserting bootstrap pins...
[2022-06-30T17:29:35Z INFO  opentitanlib::app] Asserting the reset signal
[2022-06-30T17:29:36Z INFO  opentitanlib::app] Clearing the UART RX buffer
[2022-06-30T17:29:36Z INFO  opentitanlib::app] Deasserting the reset signal
[2022-06-30T17:29:36Z INFO  opentitanlib::bootstrap] Performing bootstrap...
thread 'main' panicked at 'attempt to add with overflow', sw/host/opentitanlib/src/spiflash/sfdp.rs:449:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:48:5
   3: <opentitanlib::spiflash::sfdp::Sfdp as core::convert::TryFrom<&[u8]>>::try_from
   4: opentitanlib::spiflash::flash::SpiFlash::read_sfdp
   5: opentitanlib::spiflash::flash::SpiFlash::from_spi
   6: <opentitanlib::bootstrap::eeprom::Eeprom as opentitanlib::bootstrap::UpdateProtocol>::update
   7: opentitanlib::bootstrap::Bootstrap::do_update
   8: opentitanlib::bootstrap::Bootstrap::update_with_progress
   9: <opentitantool::command::bootstrap::BootstrapCommand as opentitanlib::app::command::CommandDispatch>::run
  10: opentitantool::_::<impl opentitanlib::app::command::CommandDispatch for opentitantool::RootCommandHierarchy>::run
  11: opentitantool::execute
  12: opentitantool::main
  13: core::ops::function::FnOnce::call_once
```

**Comment by cfrantz** [comment]
I suspect the real problem is that sfdp.rs is _a tad_ lax on error checking.  I'm not able to duplicate this on my board.  If you can duplicate it on yours, can you add the following line and let me know what you see?

```diff
$ git diff
diff --git a/sw/host/opentitanlib/src/spiflash/sfdp.rs b/sw/host/opentitanlib/src/spiflash/sfdp.rs
index dc3edfdc9..17930026f 100644
--- a/sw/host/opentitanlib/src/spiflash/sfdp.rs
+++ b/sw/host/opentitanlib/src/spiflash/sfdp.rs
@@ -444,6 +444,7 @@ impl TryFrom<&[u8]> for Sfdp {
     type Error = anyhow::Error;
     fn try_from(buf: &[u8]) -> Result<Self, Self::Error> {
         let header = SfdpHeader::try_from(buf.get(0..8).ok_or(Error::SliceRange(0, 8))?)?;
+        log::info!("header = {:x?}", header);
         let mut phdr = Vec::new();
         for i in 0..=header.nph {
             let start = (8 + i * 8) as usize;
```

You _should_ see the following:
```
opentitanlib::spiflash::sfdp] header = SfdpHeader { signature: 50444653, minor: a, major: 1, nph: 0, reserved: ff }
```

If you aren't seeing the magic number 0x50444653 in the signature field, your board isn't reporting a proper SFDP (and the SfdpHeader::try_from really _ought_ to be checking for that value, but it isn't).

**Comment by dmcardle** [comment]
Oh, interesting! I wonder what's different about mine.

Here's the output of that new log line:
```
[2022-06-30T19:13:50Z INFO  opentitanlib::spiflash::sfdp] header = SfdpHeader { signature: ffffffff, minor: ff, major: ff, nph: ff, reserved: ff }
```

Further, `buf` is actually just 256 0xff bytes.

I'll work on a regression test if that sounds good.

**Comment by cfrantz** [comment]
Seeing a value of all ones (e.g. 0xFFFFFFFF) is usually a dead giveaway for something not having been initialized.  It would be interesting to see what your board prints when you just view the console (e.g. `opentitantool console`) and press the reset button on the board (USR-RESET aka USRSW2 near the middle horizontal midpoint of the board on the bottom third).

If you haven't ever set the PLLs on your board, you may need to do that:

```
opentitantool --interface=cw310 set-pll
```

**Comment by dmcardle** [comment]
Reopening so I remember to follow up on Chris's suggestion about setting PLLs when I have physical access to the FPGA — I definitely didn't do that yet.

**Comment by dmcardle** [comment]
Setting PLLs did resolve my original issue! The test passed on cw310 (`//sw/device/tests:uart_smoketest`).

Sorry, I didn't wind up running `opentitantool console` while pressing the reset button.
