### ISSUE TITLE
Bitstream breakage that breaks the build

### ISSUE THREAD

**Issue by hcindyl** [lowRISC/opentitan#14728]
Tested at `4d3449f83a4f8`
```
$ bazel build @bitstreams//:bitstream_test_rom
WARNING:root:Closest bitstream to HEAD is 71b430567c3489fff11840071393ad8793ef99d5.
ERROR:root:Target name 'otp_mmi' for file 'cache/71b430567c3489fff11840071393ad8793ef99d5/otp.mmi' would collide with another target
INFO: Repository bitstreams instantiated at:
  /tmp/opentitan/WORKSPACE:88:16: in <toplevel>
Repository rule bitstreams_repo defined at:
  /tmp/opentitan/rules/bitstreams.bzl:52:34: in <toplevel>
ERROR: An error occurred during the fetch of repository 'bitstreams':
   Traceback (most recent call last):
	File "/tmp/opentitan/rules/bitstreams.bzl", line 25, column 13, in _bitstreams_repo_impl
		fail("Bitstream cache not initialized properly.")
Error in fail: Bitstream cache not initialized properly.
ERROR: /tmp/opentitan/WORKSPACE:88:16: fetching bitstreams_repo rule //external:bitstreams: Traceback (most recent call last):
	File "/tmp/opentitan/rules/bitstreams.bzl", line 25, column 13, in _bitstreams_repo_impl
		fail("Bitstream cache not initialized properly.")
Error in fail: Bitstream cache not initialized properly.
ERROR: Bitstream cache not initialized properly.
INFO: Elapsed time: 0.849s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by hcindyl** [comment]
Looks like a bad cache from https://github.com/lowRISC/opentitan/commit/71b430567c3489fff11840071393ad8793ef99d5. @a-will could you please help out?
