### ISSUE TITLE
Fetching for Clippy fails and stalls airgapped environments for ~60s

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#15640]
When rust rules fail to fetch https://static.rust-lang.org/dist/2022-03-22/rustc-nightly-x86_64-unknown-linux-gnu.tar.gz to build clippy they wait for the timeout to proceed before continuing which means each build stalls for ~60s

The build system kicks off a sequence of builds serially which means building n targets stalls for n*~60s which can be pretty significant.

Can we pin clippy to depend on the same version of rules_rust as OTT? Has that already happened and therefore this has a different cause?

```
(13:54:19) WARNING: Download from https://static.rust-lang.org/dist/2022-03-22/rustc-nightly-x86_64-unknown-linux-gnu.tar.gz failed: class java.io.IOException connect timed out
(13:54:19) ERROR: An error occurred during the fetch of repository 'rust_opentitan_rv32imc__riscv32imc-unknown-none-elf_tools':
   Traceback (most recent call last):
    File "/root/.cache/bazel/_bazel_maturana/41c55070b600741b0a025a37e8e9bb9c/external/rules_rust/rust/repositories.bzl", line 202, column 27, in _rust_toolchain_tools_repository_impl
        load_rust_compiler(ctx),
    File "/root/.cache/bazel/_bazel_maturana/41c55070b600741b0a025a37e8e9bb9c/external/rules_rust/rust/private/repository_utils.bzl", line 356, column 24, in load_rust_compiler
        load_arbitrary_tool(
    File "/root/.cache/bazel/_bazel_maturana/41c55070b600741b0a025a37e8e9bb9c/external/rules_rust/rust/private/repository_utils.bzl", line 628, column 42, in load_arbitrary_tool
        result = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://static.rust-lang.org/dist/2022-03-22/rustc-nightly-x86_64-unknown-linux-gnu.tar.gz] to /root/.cache/bazel/_bazel_maturana/41c55070b600741b0a025a37e8e9bb9c/external/rust_opentitan_rv32imc__riscv32imc-unknown-none-elf_tools/temp15158319428533918039/rustc-nightly-x86_64-unknown-linux-gnu.tar.gz: connect timed out
(13:54:19) ERROR: /workspace/mnt/opentitan/WORKSPACE:56:10: fetching rust_toolchain_tools_repository rule //external:rust_opentitan_rv32imc__riscv32imc-unknown-none-elf_tools: Traceback (most recent call last):
    File "/root/.cache/bazel/_bazel_maturana/41c55070b600741b0a025a37e8e9bb9c/external/rules_rust/rust/repositories.bzl", line 202, column 27, in _rust_toolchain_tools_repository_impl
        load_rust_compiler(ctx),
    File "/root/.cache/bazel/_bazel_maturana/41c55070b600741b0a025a37e8e9bb9c/external/rules_rust/rust/private/repository_utils.bzl", line 356, column 24, in load_rust_compiler
        load_arbitrary_tool(
    File "/root/.cache/bazel/_bazel_maturana/41c55070b600741b0a025a37e8e9bb9c/external/rules_rust/rust/private/repository_utils.bzl", line 628, column 42, in load_arbitrary_tool
        result = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://static.rust-lang.org/dist/2022-03-22/rustc-nightly-x86_64-unknown-linux-gnu.tar.gz] to /root/.cache/bazel/_bazel_maturana/41c55070b600741b0a025a37e8e9bb9c/external/rust_opentitan_rv32imc__riscv32imc-unknown-none-elf_tools/temp15158319428533918039/rustc-nightly-x86_64-unknown-linux-gnu.tar.gz: connect timed out
(13:54:19) ERROR: /workspace/mnt/opentitan/sw/device/lib/testing/test_rom/BUILD:28:21: //sw/device/lib/testing/test_rom:test_rom_sim_dv_scr_vmem depends on @rust_opentitan_rv32imc__riscv32imc-unknown-none-elf_tools//:rust_toolchain in repository @rust_opentitan_rv32imc__riscv32imc-unknown-none-elf_tools which failed to fetch. no such package '@rust_opentitan_rv32imc__riscv32imc-unknown-none-elf_tools//': java.io.IOException: Error downloading [https://static.rust-lang.org/dist/2022-03-22/rustc-nightly-x86_64-unknown-linux-gnu.tar.gz] to /root/.cache/bazel/_bazel_maturana/41c55070b600741b0a025a37e8e9bb9c/external/rust_opentitan_rv32imc__riscv32imc-unknown-none-elf_tools/temp15158319428533918039/rustc-nightly-x86_64-unknown-linux-gnu.tar.gz: connect timed out
(13:54:19) ERROR: Analysis of aspects '[@rules_rust//rust:defs.bzl%rust_clippy_aspect] on //sw/device/lib/testing/test_rom:test_rom_sim_dv_scr_vmem' failed; build aborted: no such package '@rust_opentitan_rv32imc__riscv32imc-unknown-none-elf_tools//': java.io.IOException: Error downloading [https://static.rust-lang.org/dist/2022-03-22/rustc-nightly-x86_64-unknown-linux-gnu.tar.gz] to /root/.cache/bazel/_bazel_maturana/41c55070b600741b0a025a37e8e9bb9c/external/rust_opentitan_rv32imc__riscv32imc-unknown-none-elf_tools/temp15158319428533918039/rustc-nightly-x86_64-unknown-linux-gnu.tar.gz: connect timed out
```

**Comment by timothytrippel** [comment]
The previous fix did not completely resolve the issue. Reopening.
