### ISSUE TITLE
tlgen.py cannot found the keyword 'clock'

### ISSUE THREAD

**Issue by gzyangcs** [lowRISC/opentitan#16752]
The command i run is 'tlgen -t ../data/xbar_main.hjson -o ~/work/opentitan/hw/top_englishbreakfast/ip --ip-path ./xbar_main/'.
Then, tlgen report below:
```
Traceback (most recent call last):
  File "/home/guozhiyang/work/opentitan/util/tlgen.py", line 94, in <module>
    main()
  File "/home/guozhiyang/work/opentitan/util/tlgen.py", line 71, in main
    xbar = tlgen.validate(obj)
  File "/home/guozhiyang/work/opentitan/util/tlgen/validate.py", line 253, in validate
    xbar.clock = obj["clock"].lower()
KeyError: 'clock'
```
I check validate.py and xbar_main.hjson, and I did not find the keyword 'clock' in addition to the keyword 'nodes' , should i change line 253 of validate.py to 'xbar.clock = obj['nodes'][n]['clock'].lower()' or 'xbar.clock = obj["clock_primary"].lower()'?

When i change line 253 to 'xbar.clock = obj["clock_primary"].lower()' and line 254 to 'xbar.reset = obj["reset_primary"].lower()', it reports below:

```
ERROR: main missing required key clock
ERROR: main missing required key reset
ERROR: main missing required key clock_connections
WARNING: main contains extra key clock_primary
WARNING: main contains extra key other_clock_list
WARNING: main contains extra key reset_primary
WARNING: main contains extra key other_reset_list
ERROR: main nodes missing required key stub
ERROR: main nodes missing required key stub
ERROR: main nodes missing required key stub
ERROR: main nodes missing required key stub
ERROR: main nodes missing required key stub
ERROR: main nodes missing required key stub
ERROR: main nodes missing required key stub
ERROR: main nodes missing required key stub
ERROR: main nodes missing required key stub
ERROR: main nodes missing required key stub
ERROR: main nodes missing required key stub
ERROR: main nodes missing required key stub
ERROR: main nodes missing required key stub
ERROR: main nodes missing required key stub
ERROR: main nodes missing required key stub
ERROR: main nodes missing required key stub
ERROR: main has top level error. Aborting
ERROR: Hjson structure error
Traceback (most recent call last):
  File "/home/guozhiyang/work/opentitan/util/tlgen.py", line 94, in <module>
    main()
  File "/home/guozhiyang/work/opentitan/util/tlgen.py", line 72, in main
    xbar.ip_path = args.ip_path
AttributeError: 'NoneType' object has no attribute 'ip_path'

```

**Comment by tjaychen** [comment]
hmmm.. .there's a chance some of the gen stuff here is a bit out dated. 
A lot of our tlgen functionality has been folded into `topgen`. 

@eunchan would know the best.

**Comment by gzyangcs** [comment]
Thanks a lot!
But, when I run topgen, it needs the absolute path of topcfg, otherwise it will give the following error:
```
Traceback (most recent call last):
  File "/home/guozhiyang/work/opentitan/util/topgen.py", line 1322, in <module>
    main()
  File "/home/guozhiyang/work/opentitan/util/topgen.py", line 1078, in main
    cfg_path = Path(args.topcfg).parents[1]
  File "/usr/lib/python3.8/pathlib.py", line 621, in __getitem__
    raise IndexError(idx)
IndexError: 1

```

In addition, running the following command will not find the keyword "module"：
`topgen -t /home/guozhiyang/work/opentitan/hw/top_englishbreakfast/data/xbar_main.hjson -o ~/work/opentitan/hw/top_englishbreakfast/ip -v --xbar-only`

reports:

```
DEBUG: Generation pass 0
Traceback (most recent call last):
  File "/home/guozhiyang/work/opentitan/util/topgen.py", line 1322, in <module>
    main()
  File "/home/guozhiyang/work/opentitan/util/topgen.py", line 1129, in main
    _process_top(cfg_copy, args, cfg_path, out_path_gen, pass_idx)
  File "/home/guozhiyang/work/opentitan/util/topgen.py", line 744, in _process_top
    templated_list = lib.get_templated_modules(topcfg)
  File "/home/guozhiyang/work/opentitan/util/topgen/lib.py", line 336, in get_templated_modules
    print(top['module'])
KeyError: 'module'
```
