### ISSUE TITLE
[bazel] Build error in tinyjson

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#20577]
### Description

Building `bazel build //sw/host/opentitantool` on Ubuntu 22.04.3 LTS with the current state on master gives me the following build error:
```
ERROR: /home/msf/.cache/bazel/_bazel_msf/a04398ae32bc4f5d6296be64a6648255/external/rules_rust_tinyjson/BUILD.bazel:4:37: in rust_library_without_process_wrapper rule @rules_rust_tinyjson//:tinyjson: 
Traceback (most recent call last):
	File "/home/msf/.cache/bazel/_bazel_msf/a04398ae32bc4f5d6296be64a6648255/external/rules_rust/rust/private/rust.bzl", line 86, column 32, in _rust_library_impl
		return _rust_library_common(ctx, "rlib")
	File "/home/msf/.cache/bazel/_bazel_msf/a04398ae32bc4f5d6296be64a6648255/external/rules_rust/rust/private/rust.bzl", line 180, column 32, in _rust_library_common
		return rustc_compile_action(
	File "/home/msf/.cache/bazel/_bazel_msf/a04398ae32bc4f5d6296be64a6648255/external/rules_rust/rust/private/rustc.bzl", line 1316, column 24, in rustc_compile_action
		ctx.actions.run(
Error in run: run() got unexpected keyword argument 'toolchain'
```

After bisecting recent changes, I found that the error occurs due to the following change in 927176403871e9504681b0dd080ae8c525411428:
```diff
--- a/third_party/rust/repos.bzl
+++ b/third_party/rust/repos.bzl
@@ -95,9 +95,9 @@ def rust_repos(rules_rust = None, safe_ftdi = None, serde_annotate = None):
     http_archive_or_local(
         name = "rules_rust",
         local = rules_rust,
-        sha256 = "e85891dd6bb24e877a9622c09f028b9e11c0f4df69db4735194eb1d8dc7ae917",
-        strip_prefix = "rules_rust-rebase-20230822_02",
-        url = "https://github.com/lowRISC/rules_rust/archive/refs/tags/rebase-20230822_02.tar.gz",
+        sha256 = "1a110ae8bfa34091e2a62e4c0325f8231f934b2956f3a585d4cafba5c81c2676",
+        strip_prefix = "rules_rust-rebase-20231115_01",
+        url = "https://github.com/lowRISC/rules_rust/archive/refs/tags/rebase-20231115_01.tar.gz",
     )
```

Any ideas what goes wrong here? I asked around and other folks do not seem to have run into this issue so far...

**Comment by msfschaffner** [comment]
CC @timothytrippel @cfrantz @nbdd0121

**Comment by msfschaffner** [comment]
I updated my toolchain and it still fails:
```
rustc --version
rustc 1.74.1 (a28077b28 2023-12-04)
```

**Comment by nbdd0121** [comment]
I can't reproduce the error. What bazel version are you using?

**Comment by msfschaffner** [comment]
I am running `bazel 5.1.1`

**Comment by a-will** [comment]
> I am running `bazel 5.1.1`

FYI, that version is not supported. The supported version is 6.2.1:

https://github.com/lowRISC/opentitan/blob/87c131a4ed3c8ab9fdf7f7e1caf8f35aed1bae8e/.bazelversion#L1

**Comment by msfschaffner** [comment]
got it, will do, thanks!

**Comment by msfschaffner** [comment]
OK I think I know why I am running this version. Our documentation still points to `5.1.1` in our docs here:
https://opentitan.org/book/doc/getting_started/build_sw.html#manual-installation

**Comment by msfschaffner** [comment]
CC @cfrantz
