### ISSUE TITLE
[tlgen] tlgen completely broken as a standalone util

### ISSUE THREAD

**Issue by luposmi** [lowRISC/opentitan#25356]
### Description

Hi, 
just wanted to say that the tlgen.py util currently always throws
```
Traceback (most recent call last):
  File "/home/krusekamp/vicuna-multicore/../repos/opentitan/util/tlgen.py", line 98, in <module>
    main()
  File "/home/krusekamp/vicuna-multicore/../repos/opentitan/util/tlgen.py", line 71, in main
    xbar = tlgen.validate(obj)
  File "/home/krusekamp/repos/opentitan/util/tlgen/validate.py", line 312, in validate
    node.addr_spaces = {nodeobj["addr_space"]}
KeyError: 'addr_space'
```
when using it as a standalone feature (where you do not generate addr_space by topgen).
To test it, just run tlgen on the example hjson file.
Before you can do that, you need to rename base_addr -> base_addrs in that file, as for some reason that part of the API was changed.

The commit 21e07594b9a789640a9d12e3268ff4e29ce76282 still works.

Have a nice day,
Ben

**Comment by rswarbrick** [comment]
Thanks for the report. The attached PR should fix things.

**Comment by luposmi** [comment]
Thanks!

Just tested it out and adapted my own config to resemble the structure of the new example, and it compiled with no issues.
