### ISSUE TITLE
[CI] Failed while installing python-requirements

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#3566]
Log is attached. CI failed at builing docker container.

```
2020-09-23T12:14:57.6102389Z Collecting mistletoe>=0.7.2 (from -r /tmp/python-requirements.txt (line 18))
2020-09-23T12:14:57.8039474Z [91mException:
2020-09-23T12:14:57.8040666Z Traceback (most recent call last):
2020-09-23T12:14:57.8042562Z   File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 377, in _make_request
2020-09-23T12:14:57.8043380Z     httplib_response = conn.getresponse(buffering=True)
2020-09-23T12:14:57.8044110Z TypeError: getresponse() got an unexpected keyword argument 'buffering'
2020-09-23T12:14:57.8044576Z 
2020-09-23T12:14:57.8044909Z During handling of the above exception, another exception occurred:
2020-09-23T12:14:57.8045371Z 
2020-09-23T12:14:57.8045633Z Traceback (most recent call last):
2020-09-23T12:14:57.8046397Z   File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 560, in urlopen
2020-09-23T12:14:57.8046855Z     body=body, headers=headers)
2020-09-23T12:14:57.8047606Z   File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 379, in _make_request
2020-09-23T12:14:57.8048112Z     httplib_response = conn.getresponse()
2020-09-23T12:14:57.8048497Z   File "/usr/lib/python3.5/http/client.py", line 1225, in getresponse
2020-09-23T12:14:57.8048846Z     response.begin()
2020-09-23T12:14:57.8049160Z   File "/usr/lib/python3.5/http/client.py", line 307, in begin
2020-09-23T12:14:57.8049544Z     version, status, reason = self._read_status()
2020-09-23T12:14:57.8049935Z   File "/usr/lib/python3.5/http/client.py", line 268, in _read_status
2020-09-23T12:14:57.8050701Z     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
2020-09-23T12:14:57.8051441Z   File "/usr/lib/python3.5/socket.py", line 575, in readinto
2020-09-23T12:14:57.8051939Z     return self._sock.recv_into(b)
2020-09-23T12:14:57.8052244Z   File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
2020-09-23T12:14:57.8052566Z     return self.read(nbytes, buffer)
2020-09-23T12:14:57.8052868Z   File "/usr/lib/python3.5/ssl.py", line 791, in read
2020-09-23T12:14:57.8053198Z     return self._sslobj.read(len, buffer)
2020-09-23T12:14:57.8053879Z   File "/usr/lib/python3.5/ssl.py", line 575, in read
2020-09-23T12:14:57.8054178Z     v = self._sslobj.read(len, buffer)
2020-09-23T12:14:57.8054906Z ConnectionResetError: [Errno 104] Connection reset by peer
2020-09-23T12:14:57.8055143Z 
2020-09-23T12:14:57.8055455Z During handling of the above exception, another exception occurred:
2020-09-23T12:14:57.8055901Z 
2020-09-23T12:14:57.8056156Z Traceback (most recent call last):
2020-09-23T12:14:57.8056776Z   File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
2020-09-23T12:14:57.8057155Z     status = self.run(options, args)
2020-09-23T12:14:57.8057974Z   File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 328, in run
2020-09-23T12:14:57.8058594Z     wb.build(autobuilding=True)
2020-09-23T12:14:57.8059243Z   File "/usr/lib/python3/dist-packages/pip/wheel.py", line 748, in build
2020-09-23T12:14:57.8059649Z     self.requirement_set.prepare_files(self.finder)
2020-09-23T12:14:57.8060249Z   File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 360, in prepare_files
2020-09-23T12:14:57.8060669Z     ignore_dependencies=self.ignore_dependencies))
2020-09-23T12:14:57.8061279Z   File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 512, in _prepare_file
2020-09-23T12:14:57.8061660Z     finder, self.upgrade, require_hashes)
2020-09-23T12:14:57.8062266Z   File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 273, in populate_link
2020-09-23T12:14:57.8062694Z     self.link = finder.find_requirement(self, upgrade)
2020-09-23T12:14:57.8063286Z   File "/usr/lib/python3/dist-packages/pip/index.py", line 442, in find_requirement
2020-09-23T12:14:57.8063712Z     all_candidates = self.find_all_candidates(req.name)
2020-09-23T12:14:57.8064325Z   File "/usr/lib/python3/dist-packages/pip/index.py", line 400, in find_all_candidates
2020-09-23T12:14:57.8064782Z     for page in self._get_pages(url_locations, project_name):
2020-09-23T12:14:57.8065548Z   File "/usr/lib/python3/dist-packages/pip/index.py", line 545, in _get_pages
2020-09-23T12:14:57.8065931Z     page = self._get_page(location)
2020-09-23T12:14:57.8066482Z   File "/usr/lib/python3/dist-packages/pip/index.py", line 648, in _get_page
2020-09-23T12:14:57.8066892Z     return HTMLPage.get_page(link, session=self.session)
2020-09-23T12:14:57.8067469Z   File "/usr/lib/python3/dist-packages/pip/index.py", line 757, in get_page
2020-09-23T12:14:57.8068030Z     "Cache-Control": "max-age=600",
2020-09-23T12:14:57.8068699Z   File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 480, in get
2020-09-23T12:14:57.8069354Z     return self.request('GET', url, **kwargs)
2020-09-23T12:14:57.8070034Z   File "/usr/lib/python3/dist-packages/pip/download.py", line 378, in request
2020-09-23T12:14:57.8070476Z     return super(PipSession, self).request(method, url, *args, **kwargs)
2020-09-23T12:14:57.8071181Z   File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 468, in request
2020-09-23T12:14:57.8071622Z     resp = self.send(prep, **send_kwargs)
2020-09-23T12:14:57.8072274Z   File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 597, in send
2020-09-23T12:14:57.8072729Z     history = [resp for resp in gen] if allow_redirects else []
2020-09-23T12:14:57.8073480Z   File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 597, in <listcomp>
2020-09-23T12:14:57.8073964Z     history = [resp for resp in gen] if allow_redirects else []
2020-09-23T12:14:57.8074670Z   File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 195, in resolve_redirects
2020-09-23T12:14:57.8075102Z     **adapter_kwargs
2020-09-23T12:14:57.8075722Z   File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 576, in send
2020-09-23T12:14:57.8076141Z     r = adapter.send(request, **kwargs)
2020-09-23T12:14:57.8077020Z   File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/adapter.py", line 46, in send
2020-09-23T12:14:57.8082128Z     resp = super(CacheControlAdapter, self).send(request, **kw)
2020-09-23T12:14:57.8083290Z   File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/adapters.py", line 376, in send
2020-09-23T12:14:57.8083861Z     timeout=timeout
2020-09-23T12:14:57.8084967Z   File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 610, in urlopen
2020-09-23T12:14:57.8085523Z     _stacktrace=sys.exc_info()[2])
2020-09-23T12:14:57.8086475Z   File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 228, in increment
2020-09-23T12:14:57.8087353Z     total -= 1
2020-09-23T12:14:57.8088062Z TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
```
[2020-09-23-ci-failure.log](https://github.com/lowRISC/opentitan/files/5269936/2020-09-23-ci-failure.log)

**Comment by lenary** [comment]
@eunchan I *think* you just need to re-run the CI job - apparently the real error here is the `ConnectionResetError: [Errno 104] Connection reset by peer`, rather than the other messages.

**Comment by eunchan** [comment]
Uh-oh... you are right. :)

**Comment by lenary** [comment]
I do think this isn't an obvious fix, and I wish the job wasn't so flaky, thanks for raising it as a concern.

**Comment by rswarbrick** [comment]
I spent some time on this problem a couple of weeks ago. Part of the problem is that the (ancient) version of urllib3 has slightly dubious Python2 / Python3 support. Basically, they try running `httplib_response = conn.getresponse(buffering=True)` (which is valid for Python2 from version 2.7) and if they get an error, they try `httplib_response = conn.getresponse()` (which is valid for Python <= 2.6 OR Python 3). Unfortunately, they forgot the `... from None` incantation that hides the original code in a backtrace if something else goes wrong, leading to massively confusing backtraces like this one. This is fixed in more modern versions of urllib3, which we'll get if and when we upgrade our machines from Ubuntu 16.04.

Anyway, that means you should start reading the traceback at "During handling of the above exception...". From there, it seems that urllib3 has passed a "Retry" object where the code was expecting an integer. No idea what's going on there, but I'd put money on this being fixed if we upgrade.
