### ISSUE TITLE
Tracing in Verilator simulation with --trace broken (segfault)

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#3951]
When running a Verilator simulation with `--trace` to get a FST trace the simulation segfaults. This happens with both Verilator 4.040 and the latest master version.

A git bisect shows commit d052f1c0f6cfd026a1d7c2b3fd1ef360a94d0a0e ([verilator] Update to use sim SRAM area for exit) triggering the segfault (merged in https://github.com/lowRISC/opentitan/pull/3782).

Backtrace:

```
Simulation running, end by pressing CTRL-c.
Tracing enabled.
Writing simulation traces to sim.fst

Thread 1 "Vtop_earlgrey_v" received signal SIGSEGV, Segmentation fault.
fstWriterEmitValueChange (ctx=0x1c53440, handle=4294967295, val=val@entry=0x7ffffffd0590) at /home/philipp/swinstall/verilator/share/verilator/include/gtkwave/fstapi.c:2934
2934            len  = vm4ip[1];
(gdb) bt
#0  fstWriterEmitValueChange (ctx=0x1c53440, handle=4294967295, val=val@entry=0x7ffffffd0590) at /home/philipp/swinstall/verilator/share/verilator/include/gtkwave/fstapi.c:2934
#1  0x0000000000433604 in VerilatedFst::emitIData (bits=<optimized out>, newval=<optimized out>, code=<optimized out>, this=<optimized out>)
    at /home/philipp/swinstall/verilator/share/verilator/include/verilated_fst_c.cpp:233
#2  VerilatedTrace<VerilatedFst>::fullIData (this=<optimized out>, oldp=<optimized out>, newval=<optimized out>, bits=<optimized out>)
    at /home/philipp/swinstall/verilator/share/verilator/include/verilated_trace_imp.cpp:532
#3  0x0000000000b3f026 in Vtop_earlgrey_verilator::traceFullSub0 (userp=0x7ffff797b040, tracep=0x1c4d1f0) at Vtop_earlgrey_verilator__Trace__4__Slow.cpp:14406
#4  0x0000000000b31d3f in Vtop_earlgrey_verilator::traceFullTop0 (userp=0x7ffff797b040, tracep=0x1c4d1f0) at Vtop_earlgrey_verilator__Trace__4__Slow.cpp:12934
#5  0x000000000043344d in VerilatedTrace<VerilatedFst>::dump (this=0x1c4d1f0, timeui=<optimized out>)
    at /home/philipp/swinstall/verilator/share/verilator/include/verilated_trace_imp.cpp:444
#6  0x0000000000410aaf in VerilatorSimCtrl::Run (this=this@entry=0x1c2a140 <VerilatorSimCtrl::GetInstance()::instance>)
    at ../src/lowrisc_dv_verilator_simutil_verilator_0/cpp/verilator_sim_ctrl.cc:281
#7  0x0000000000410c3d in VerilatorSimCtrl::RunSimulation (this=0x1c2a140 <VerilatorSimCtrl::GetInstance()::instance>)
    at ../src/lowrisc_dv_verilator_simutil_verilator_0/cpp/verilator_sim_ctrl.cc:129
#8  0x0000000000410cf1 in VerilatorSimCtrl::Exec (this=this@entry=0x1c2a140 <VerilatorSimCtrl::GetInstance()::instance>, argc=argc@entry=6, argv=argv@entry=0x7fffffffd0a8)
    at ../src/lowrisc_dv_verilator_simutil_verilator_0/cpp/verilator_sim_ctrl.cc:48
#9  0x000000000040858b in main (argc=6, argv=0x7fffffffd0a8) at ../src/lowrisc_systems_top_earlgrey_verilator_0.1/top_earlgrey_verilator.cc:39
```

I'll keep trying to narrow down the problem a bit more. Fortunately, the relevant commit isn't large.

**Comment by sriyerg** [comment]
I found the fix for this. Will push soon.

**Comment by imphil** [comment]
In #3955 @sriyerg has found a simple workaround for it. We should still file an upstream Verilator bug, but reducing the testcase will take a bit of time (something to do with binds).
