### ISSUE TITLE
[reg] auto added parameter's default value has wrong type

### ISSUE THREAD

**Issue by bluewww** [lowRISC/opentitan#4240]
Looking through the `hjson` files in this code base I got the impression that the `default` key in a `param_list` needs to contain a string type as value (seems to be always an integer-as-string).

It seems like that in `validate.py` of the regtool we get an actualy python integer type put as value in the fallback code path that auto adds a parameter when required.
https://github.com/lowRISC/opentitan/blob/87f01a7dd46b7de06aecfba4b50badfbd9db8b6a/util/reggen/validate.py#L54

`mcount` should be cast to a string (`str(mcount)`) instead.

This prevents a crash when invoking `regtool.py --cdefines` on this
```hjson
{
    name: "example",
    clock_primary: "clk_i",
    reset_primary: "rst_ni",
    bus_device: "reg",
    bus_host: "",

    regwidth: "32",
    registers: [
        { multireg:
          { name: "OP_A",
            desc: "Subword of Operand A.",
            count: "8",
            cname: "OP_A",
            swaccess: "wo",
            fields: [
                { bits: "31:0"
                }
            ],
          }
        },
    ],
}
```

Error log
```
Traceback (most recent call last):
  File "./regtool.py", line 235, in <module>
    main()
  File "./regtool.py", line 225, in main
    gen_cheader.gen_cdefines(obj, outfile, src_lic, src_copy)
  File "/home/bluew/projects/register_interface/vendor/lowrisc_opentitan/util/reggen/gen_cheader.py", line 327, in gen_cdefines
    gen_cdefines_module_params(outstr, regs, component, regwidth,
  File "/home/bluew/projects/register_interface/vendor/lowrisc_opentitan/util/reggen/gen_cheader.py", line 210, in gen_cdefines_module_params
    gen_cdefines_module_param(outstr, param, module_name, existing_defines)
  File "/home/bluew/projects/register_interface/vendor/lowrisc_opentitan/util/reggen/gen_cheader.py", line 188, in gen_cdefines_module_param
    define = gen_define(define_name, [], param['default'],
  File "/home/bluew/projects/register_interface/vendor/lowrisc_opentitan/util/reggen/gen_cheader.py", line 82, in gen_define
    oneline_define = define_declare + ' ' + body
TypeError: can only concatenate str (not "int") to str
```

**Comment by rswarbrick** [comment]
This shouldn't be relevant any more, I hope: The reggen code has been heavily re-worked and is now a bit more principled about types.
