### ISSUE TITLE
[fpga] CW310 sporadic USB hang when setting PLLs 

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#6878]
We use the CW310 board in CI and frequently flash the bitstream and load OpenTitan software over SPI (spiflash). All board interaction is going through cw310_loader.py (https://github.com/lowRISC/opentitan/blob/master/util/fpga/cw310_loader.py), which uses the ChipWhisperer Python APIs.

In most cases, this works fine.

However, in some cases (like 1 in 100 runs) the board "hangs" over USB, i.e. it doesn't respond over USB any more. Even though this is a tricky problem to debug, we need to find a way to make it work reliably with a much lower failure probability.

What I know so far:
* The failures we've seen so far are happening when loading the software over SPI ("spiflash"), not when flashing the FPGA bitstream.
* All board interaction is done from a Docker container, but I don't see anything indicating that this is causing problems. Neither the system, nor the container logs show any USB-related messages.
* In the error cases we've seen, we had successful board interactions *in the same container run* preceding the failing ones.

Below is a log from a failing run where we tried to flash OpenTitan software onto the OpenTitan system. The bitstream was loaded earlier, and the same spiflash operation, with another software binary, was successful just seconds ago.

Command:
```
stdbuf -oL /azp/agent/_work/1/s/util/fpga/cw310_loader.py --firmware /azp/agent/_work/1/a/build-bin/sw/device/tests/dif_clkmgr_smoketest_fpga_nexysvideo.bin
```

STDOUT:
```
2021-06-08T02:13:36.0167869Z DEBUG    root:utils.py:363 CW310 Loader: Attemping to find CW310 FPGA Board:
2021-06-08T02:13:36.0169054Z DEBUG    root:utils.py:363     No bitstream specified
2021-06-08T02:13:36.0170184Z DEBUG    root:utils.py:363 Board found, setting PLL2 to 100 MHz
```

STDERR:
```
2021-06-08T02:13:39.2189113Z DEBUG    root:utils.py:363 Traceback (most recent call last):
2021-06-08T02:13:39.2190189Z DEBUG    root:utils.py:363   File "/azp/agent/_work/1/s/util/fpga/cw310_loader.py", line 65, in <module>
2021-06-08T02:13:39.2191050Z DEBUG    root:utils.py:363     main()
2021-06-08T02:13:39.2192104Z DEBUG    root:utils.py:363   File "/azp/agent/_work/1/s/util/fpga/cw310_loader.py", line 54, in main
2021-06-08T02:13:39.2193275Z DEBUG    root:utils.py:363     target.pll.pll_outfreq_set(100E6, 2)
2021-06-08T02:13:39.2195078Z DEBUG    root:utils.py:363   File "/root/.local/lib/python3.6/site-packages/chipwhisperer/hardware/naeusb/pll_cdce906.py", line 53, in pll_outfreq_set
2021-06-08T02:13:39.2196447Z DEBUG    root:utils.py:363     self.pllwrite(outnum, N=best[0], M=best[1], outdiv=best[2])
2021-06-08T02:13:39.2198074Z DEBUG    root:utils.py:363   File "/root/.local/lib/python3.6/site-packages/chipwhisperer/hardware/naeusb/pll_cdce906.py", line 338, in pllwrite
2021-06-08T02:13:39.2199255Z DEBUG    root:utils.py:363     self.cdce906write(13 + pllnum, outdiv & 0x7F)
2021-06-08T02:13:39.2200847Z DEBUG    root:utils.py:363   File "/root/.local/lib/python3.6/site-packages/chipwhisperer/hardware/naeusb/pll_cdce906.py", line 235, in cdce906write
2021-06-08T02:13:39.2202199Z DEBUG    root:utils.py:363     resp = self._usb.readCtrl(0x30, dlen=2)
2021-06-08T02:13:39.2203748Z DEBUG    root:utils.py:363   File "/root/.local/lib/python3.6/site-packages/chipwhisperer/hardware/naeusb/naeusb.py", line 796, in readCtrl
2021-06-08T02:13:39.2204941Z DEBUG    root:utils.py:363     return self.usbseralizer.readCtrl(cmd, value, dlen)
2021-06-08T02:13:39.2206364Z DEBUG    root:utils.py:363   File "/root/.local/lib/python3.6/site-packages/chipwhisperer/hardware/naeusb/naeusb.py", line 191, in readCtrl
2021-06-08T02:13:39.2207535Z DEBUG    root:utils.py:363     return self.process_rx(self.txrx(tx=cmdpacket))
2021-06-08T02:13:39.2208854Z DEBUG    root:utils.py:363   File "/root/.local/lib/python3.6/site-packages/chipwhisperer/hardware/naeusb/naeusb.py", line 299, in txrx
2021-06-08T02:13:39.2210325Z DEBUG    root:utils.py:363     response = self.usbdev().ctrl_transfer(payload[0], payload[1], payload[2], payload[3], payload[4], timeout=self._timeout)
2021-06-08T02:13:39.2211777Z DEBUG    root:utils.py:363   File "/usr/local/lib/python3.6/dist-packages/usb/core.py", line 1079, in ctrl_transfer
2021-06-08T02:13:39.2212627Z DEBUG    root:utils.py:363     self.__get_timeout(timeout))
2021-06-08T02:13:39.2213866Z DEBUG    root:utils.py:363   File "/usr/local/lib/python3.6/dist-packages/usb/backend/libusb1.py", line 901, in ctrl_transfer
2021-06-08T02:13:39.2214750Z DEBUG    root:utils.py:363     timeout))
2021-06-08T02:13:39.2215986Z DEBUG    root:utils.py:363   File "/usr/local/lib/python3.6/dist-packages/usb/backend/libusb1.py", line 602, in _check
2021-06-08T02:13:39.2217002Z DEBUG    root:utils.py:363     raise USBTimeoutError(_strerror(ret), ret, _libusb_errno[ret])
2021-06-08T02:13:39.2217959Z DEBUG    root:utils.py:363 usb.core.USBTimeoutError: [Errno 110] Operation timed out
```

Full log: [196.txt](https://github.com/lowRISC/opentitan/files/6615518/196.txt) ([original run](https://dev.azure.com/lowrisc/4c50229e-f6cb-4f39-8522-585bb3841438/_apis/build/builds/43240/logs/196)) [failing pipeline](https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=43240&view=logs&j=be0b5a13-ded6-5a2a-3e48-80a10e7eef12&t=2aaa9e8b-9b00-5802-e0c1-7bc55418740f)

This log output indicates that the board is OK at the beginning of the operation, but then fails when setting a particular clock in line 54:

https://github.com/lowRISC/opentitan/blob/c49ae2cefc95813dcde270243a37893746f36afc/util/fpga/cw310_loader.py#L54

The script ties to set another clock immediately before the failing operation, which apparently was successful.

Manually running `lsusb -v`, which also tries to access the USB device, agrees with the device "not responding". Here's the log: [report.txt](https://github.com/lowRISC/opentitan/files/6615512/report.txt)

My first guess would be that the reconfigured PLL somehow affected the USB operation.

@colinoflynn I know that's not a lot of information, but is there something you could think of to debug this further?

**Comment by colinoflynn** [comment]
No that is good - should be able to run a stress test of it to see if we can shake this out. FYI - the PLL communication triggers some I2C traffic on the board. So if this is hanging somehow it may error out the USB, as I suspect it gets stuck "waiting forever" for some I2C ACK or similar. It might be a timing collision if there is another I2C transaction in process for example (the board polls the FPGA temp, also using the same I2C bus, I thought it was guarded but it makes me wonder if it collides with a temp poll & PLL read).

If you need a work-around: the PLL has EEPROM to set a default frequency. I can add that as an option to the loader & you could call that once on the board, then comment it out so it's not called everything. From then on the board will always come up with your requested frequency.

**Comment by colinoflynn** [comment]
I've implemented the work-around here: https://github.com/newaetech/opentitan/commit/531520465e8dc8c0ba999bf475fcb8699e4db135 . I can start a PR for that if useful, or just steal it for now.

You'll need to run the board once with the `--set-pll-defaults` flag, after that it should come up with the same frequency setting in the future.

**Comment by imphil** [comment]
Thanks @colinoflynn! Would you mind doing a PR with that commit? We need to get it into the master tree to be used in the CI runs.

I'll then do a one-off run with the PLL setting after we reset the FPGA board.

**Comment by imphil** [comment]
Status update: as a workaround, we now avoid setting the PLL configuration for every run (PR #6879) in CI, but set the configuration manually when we connect the FPGA board to the CI runner. If that gives us more reliable connections then we have at least found the high-level problem. Time will tell.

Thanks @colinoflynn so far for your rapid response, much appreciated!

**Comment by colinoflynn** [comment]
I opened a new issue on the main cw310 repo - however I can confirm I can trigger this bug by just looping the PLL code. So that makes it easy for us to reproduce - I'll leave any more details in the newaetech/cw310-bergen-board issue as we fix it. I'll update this issue here with anything major (hopefully - new firmware available for SAM3X that fixes it).

**Comment by imphil** [comment]
> I can confirm I can trigger this bug by just looping the PLL code

That's good to hear! Easy to reproduce bugs are the best :smile:

**Comment by colinoflynn** [comment]
This is fixed with a new firmware update at https://github.com/newaetech/cw310-bergen-board/tree/main/microfw/CW310/Debug - if you only update the FW it will now cause an error when the issue occurs. The firmware update mechanism is described at https://rtfm.newae.com/Targets/CW310%20Bergen%20Board/#firmware-upgrade.

A matching update to the ChipWhisperer software (currently not in the main branch) does a smart-retry, so you won't see the error in most usage. But if you need the feature for some reason let me know & can detail this, otherwise it will get fixed in the next (or so) release.

**Comment by imphil** [comment]
Thanks a lot @colinoflynn! Unless you need more testing for the firmware, I'll wait with the update until the SW change has hit the develop branch (or made it into a release).

With the workaround we have in place right now, which avoids setting the PLLs at all, we got reliable testing for the last week or so (with around 250 test jobs processed), which removes the urgency from this issue and gives you time to come up with a fix without time pressure.

**Comment by moidx** [comment]
Marking as M2 Milestone for further triaging.

**Comment by a-will** [comment]
Closing, as this is an issue in the CW310's SAM3X firmware, and the upstream bug (https://github.com/newaetech/cw310-bergen-board/issues/3) is marked closed.
