### ISSUE TITLE
[dvsim] KeyError: <SimCfg.SimCfg object at 0x7f16327f7700>

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#7289]
When running in GUI mode with more than one test I get the following error. (It works fine without `--gui``):

```
❯ util/dvsim/dvsim.py hw/ip/otbn/dv/uvm/otbn_sim_cfg.hjson -i smoke --fixed-seed 1 --waves --gui
INFO: [dvsim] [proj_root]: /home/philipp/src/opentitan
INFO: [SimCfg] [scratch_path]: [otbn] [/home/philipp/src/opentitan/scratch/otbn-lc-escalate-routing/otbn-sim-vcs]
WARNING: [SimCfg] In GUI mode, only one test is allowed to run. Picking otbn:0.otbn_smoke.1




         [   legend    ]: [Q: queued, D: dispatched, P: passed, F: failed, K: killed, T: total]                                                                                             
Traceback (most recent call last):
  File "util/dvsim/dvsim.py", line 704, in <module>
    main()
  File "util/dvsim/dvsim.py", line 685, in main
    results = cfg.deploy_objects()
  File "/home/philipp/src/opentitan/util/dvsim/FlowCfg.py", line 382, in deploy_objects
    return Scheduler(deploy, get_launcher_cls()).run()
  File "/home/philipp/src/opentitan/util/dvsim/Scheduler.py", line 155, in run
    changed = self._poll(hms) or timer.check_time()
  File "/home/philipp/src/opentitan/util/dvsim/Scheduler.py", line 392, in _poll
    self._enqueue_successors(item)
  File "/home/philipp/src/opentitan/util/dvsim/Scheduler.py", line 238, in _enqueue_successors
    for next_item in self._get_successors(item):
  File "/home/philipp/src/opentitan/util/dvsim/Scheduler.py", line 283, in _get_successors
    for next_item in self._scheduled[target][cfg]:
KeyError: <SimCfg.SimCfg object at 0x7f16327f7700>
```

@sriyerg

**Comment by rswarbrick** [comment]
Hmm, not sure what was going on there but I've used gui mode successfully more recently. Probably not worth digging into this now, since it's hopefully fixed.
